### ISSUE TITLE
jump's repl doesn't show up running node 0.6.x

### ISSUE THREAD

**Issue by fhemberger** [friggeri/jump#5]
A few weeks ago I updated node to 0.6 and it seems to be the reason jump doesn't work for me any longer.
When I run the `jump` or `j`command, the repl with the leading > doesn't show up. I can type things into STDIN but nothing happens.

```
➜ ~ node -v
v0.6.2
➜ ~ npm -v
1.0.104
➜ ~ jump -v
-bash: cd: 0.0.5: No such file or directory
```

(The last line looks also strange)

**Comment by friggeri** [comment]
I'm aware of this bug but haven't been able to find where it came from yet. I guess it has something to do with node 0.6.2 breaking some king of API that charm uses. For the time being stick with an older version of node. If you manage to find the bug, please submit a patch.

**Comment by fhemberger** [comment]
Looks like the `keypress` event is now only fired after you pressed enter:

```
process.stdin.resume();
process.stdin.setEncoding('utf8');

process.stdin.on('keypress', function(chr, key) {
  process.stdout.write(chr);
});
```

Maybe this helps: http://stackoverflow.com/questions/5006821/nodejs-how-to-read-keystrokes-from-stdin

**Comment by friggeri** [comment]
The problem actually comes from a charm, I've filled substack/node-charm#5, waiting to hear from @substack.

**Comment by ghost** [comment]
`tty.setRawMode(true)`?

**Comment by friggeri** [comment]
Isn't `tty.setRawMode` already called by charm ?
