### ISSUE TITLE
throw e; // process.nextTick error, or 'error' event on first tick

### ISSUE THREAD

**Issue by tristan-k** [friggeri/jump#7]
Hi there,

I'm using node 0.4.12 and the jump installation went fine but typing j followed by an enter command results in:

> $ j
> 
> node.js:134
>         throw e; // process.nextTick error, or 'error' event on first tick
>         ^
> TypeError: Object #<ReadStream> has no method 'setRawMode'
>     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/jump/node_modules/charm/index.js:43:23)
>     at /usr/local/lib/node_modules/jump/node_modules/charm/index.js:29:12
>     at Object.<anonymous> (/usr/local/lib/node_modules/jump/jump.js:32:34)
>     at Module._compile (module.js:411:26)
>     at Object..js (module.js:417:10)
>     at Module.load (module.js:343:31)
>     at Function._load (module.js:302:12)
>     at Array.<anonymous> (module.js:430:10)
>     at EventEmitter._tickCallback (node.js:126:26)

Here's what the terminal showed after the jump installation:

> $ npm -g install jump
> /usr/local/bin/jump -> /usr/local/lib/node_modules/jump/jump.js
> jump@0.1.0 /usr/local/lib/node_modules/jump 
> ├── charm@0.0.6
> └── commander@0.6.0

Any suggestions or do you recommend a specific node version? A "brew versions node" shows many versions.

> $ brew versions node
> 0.8.1    git checkout 9ff0a1d /usr/local/Library/Formula/node.rb
> 0.8.0    git checkout 01f8006 /usr/local/Library/Formula/node.rb
> 0.6.19   git checkout 83988e4 /usr/local/Library/Formula/node.rb
> 0.6.18   git checkout 653fb77 /usr/local/Library/Formula/node.rb
> 0.6.17   git checkout a3ecde3 /usr/local/Library/Formula/node.rb
> 0.6.16   git checkout ed17582 /usr/local/Library/Formula/node.rb
> 0.6.15   git checkout e18b02f /usr/local/Library/Formula/node.rb
> 0.6.14   git checkout 30813c8 /usr/local/Library/Formula/node.rb
> 0.6.13   git checkout 3b771d0 /usr/local/Library/Formula/node.rb
> 0.6.12   git checkout 0e8ea8a /usr/local/Library/Formula/node.rb
> 0.6.11   git checkout 3eec1f4 /usr/local/Library/Formula/node.rb
> 0.6.10   git checkout 7e202eb /usr/local/Library/Formula/node.rb
> 0.6.9    git checkout f752570 /usr/local/Library/Formula/node.rb
> 0.6.8    git checkout 74bff39 /usr/local/Library/Formula/node.rb
> 0.6.7    git checkout 9a52dcf /usr/local/Library/Formula/node.rb
> 0.6.6    git checkout 97fce9a /usr/local/Library/Formula/node.rb
> 0.6.5    git checkout 911726f /usr/local/Library/Formula/node.rb
> 0.6.4    git checkout 67a2615 /usr/local/Library/Formula/node.rb
> 0.6.2    git checkout 05b94b9 /usr/local/Library/Formula/node.rb
> 0.6.1    git checkout b6eb4fc /usr/local/Library/Formula/node.rb
> 0.6.0    git checkout 6bec7fc /usr/local/Library/Formula/node.rb
> 0.4.12   git checkout 3eea412 /usr/local/Library/Formula/node.rb
> 0.4.11   git checkout b6aa338 /usr/local/Library/Formula/node.rb
> 0.4.10   git checkout 523d360 /usr/local/Library/Formula/node.rb
> 0.4.9    git checkout 10b3ded /usr/local/Library/Formula/node.rb
> 0.4.8    git checkout 8d45d93 /usr/local/Library/Formula/node.rb
> 0.4.7    git checkout cb6a4b4 /usr/local/Library/Formula/node.rb
> 0.4.6    git checkout 7c0f0d9 /usr/local/Library/Formula/node.rb
> 0.4.5    git checkout 8241b81 /usr/local/Library/Formula/node.rb
> 0.4.4    git checkout 83753a9 /usr/local/Library/Formula/node.rb
> 0.4.3    git checkout f4a925d /usr/local/Library/Formula/node.rb
> 0.4.2    git checkout 0476235 /usr/local/Library/Formula/node.rb
> 0.4.1    git checkout 8a60de4 /usr/local/Library/Formula/node.rb
> 0.4.0    git checkout b4497ec /usr/local/Library/Formula/node.rb
> 0.2.6    git checkout 8602eee /usr/local/Library/Formula/node.rb
> 0.3.2    git checkout 168cb3d /usr/local/Library/Formula/node.rb
> 0.2.5    git checkout f55f417 /usr/local/Library/Formula/node.rb
> 0.2.4    git checkout 89438ae /usr/local/Library/Formula/node.rb
> 0.2.3    git checkout 730f311 /usr/local/Library/Formula/node.rb
> 0.2.2    git checkout 981bb41 /usr/local/Library/Formula/node.rb
> 0.2.1    git checkout c963a35 /usr/local/Library/Formula/node.rb
> 0.2.0    git checkout fbb93d9 /usr/local/Library/Formula/node.rb
> 0.1.104  git checkout ed51a5b /usr/local/Library/Formula/node.rb
> 0.1.103  git checkout f3e7c1b /usr/local/Library/Formula/node.rb
> 0.1.20   git checkout 2baa60c /usr/local/Library/Formula/node.rb
> 0.1.17   git checkout ab7697f /usr/local/Library/Formula/node.rb
> 0.1.14   git checkout a82e823 /usr/local/Library/Formula/node.rb

**Comment by tristan-k** [comment]
In this Issue https://github.com/afriggeri/jump/issues/6 you recommend node 0.7.7 which isnt available on brew. Node 0.8.1 doesnt work with npm so my hands are tied ...

**Comment by friggeri** [comment]
I currently use jump with node 0.8.0. Would that work for you?

**Comment by tristan-k** [comment]
No not at all. Here is my complete install routine for node and npm:

> $ cd /usr/local/
> $ git checkout 01f8006 /usr/local/Library/Formula/node.rb
> $ brew install node
> $ export NODE_PATH="/usr/local/lib/node_modules"
> $ export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/npm/bin:$PATH"
> $ curl http://npmjs.org/install.sh | sh
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  7881  100  7881    0     0  15341      0 --:--:-- --:--:-- --:--:-- 25587
> tar=/usr/bin/tar
> version:
> bsdtar 2.8.3 - libarchive 2.8.3
> install npm@1.1
> fetching: http://registry.npmjs.org/npm/-/npm-1.1.35.tgz
> 0.8.0
> 1.1.35
> cleanup prefix=/usr/local

All clean!

> npm@1.1.35 prepublish .
> npm prune ; make -j4 doc

sh: npm: command not found
make: Nothing to be done for `doc'.
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@1.1.35 /usr/local/lib/node_modules/npm
It worked

> $ npm -g install jump
> npm http GET https://registry.npmjs.org/jump
> npm http 304 https://registry.npmjs.org/jump
> npm http GET https://github.com/afriggeri/node-charm/tarball/master
> npm http GET https://github.com/afriggeri/commander.js/tarball/master
> npm http 200 https://github.com/afriggeri/commander.js/tarball/master
> npm http 200 https://github.com/afriggeri/node-charm/tarball/master
> npm WARN engine commander@0.6.0: wanted: {"node":">= 0.4.x < 0.8.0"} (current: {"node":"0.8.0","npm":"1.1.35"})
> /usr/local/bin/jump -> /usr/local/lib/node_modules/jump/jump.js
> charm@0.0.6 /usr/local/lib/node_modules/jump/node_modules/charm

commander@0.6.0 /usr/local/lib/node_modules/jump/node_modules/commander

jump@0.1.0 /usr/local/lib/node_modules/jump

> $ jump >> ~/.bash_profile && source ~/.bash_profile
> $ j

At this point the terminal freezes with ">" at the front and nothing happens until I kill the "node /usr/local/bin/jump -a" process.
Running the node command alone doesn't freeze the terminal. So there must be something wrong in the way jump communicates with node. Pardon my vocabulary, but I don't code.

**Comment by friggeri** [comment]
Could you try again ? I've updated the custom commander version I use in jump.

**Comment by tristan-k** [comment]
> $ npm -g uninstall jump
> $ npm -g install jump
> npm http GET https://registry.npmjs.org/jump
> npm http 304 https://registry.npmjs.org/jump
> npm http GET https://github.com/afriggeri/node-charm/tarball/master
> npm http GET https://github.com/afriggeri/commander.js/tarball/master
> npm http 200 https://github.com/afriggeri/commander.js/tarball/master
> npm http 200 https://github.com/afriggeri/node-charm/tarball/master
> /usr/local/bin/jump -> /usr/local/lib/node_modules/jump/jump.js
> charm@0.0.6 /usr/local/lib/node_modules/jump/node_modules/charm

commander@0.6.0 /usr/local/lib/node_modules/jump/node_modules/commander

jump@0.1.0 /usr/local/lib/node_modules/jump

Still the same. Terminal freezes.

**Comment by friggeri** [comment]
Just realized I had not published the latest version to npm, could you try one last time to npm uninstall / npm install?

**Comment by tristan-k** [comment]
works fine now, although I have to say it isn't as clever as spotlight. for example typing "j" followed by mp4 doesn't bring me to the directory where my mp4 files are. It also seems as externals storages which are index by mdfind are ignored, is that true?
